import { CompanyData } from '../company';
import { CustomFields } from '../custom_fields';
import { WorkStatus } from '../enum/work_status';
import { Gender } from '../enum/gender';
import { IdentityNumberType } from '../enum/identity-number-type';
import { Status } from '../enum/status';

export interface Employee {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  workStatus: WorkStatus;
  imageProfileUrl: string;
  code: number;
  pin: number;
  phone: string;
  company: CompanyData;
  gender: Gender;
  contractId: string;
  nid: number;
  identityNumberType: IdentityNumberType;
  ssn: string;
  pricePerHour: number;
  accountNumber: string;
  dateOfBirth: string;
  customFields: CustomFields;
  createdAt: string;
  updatedAt: string;
  status: Status;
  children: number;
  disability: number;
  address: string;
  postalCode: string;
  city: string;
  province: string;
  country: string;
  nationality: string;
  personalMail: string;
  maritalStatus: string;
  emergencyPhone: string;
  description: string;
  salaryRange: string;
  studyLevel: string;
  professionalCategoryCode: string;
  professionalCategoryDescription: string;
  bic: string;
  jobChargeId: string;
  jobChargeName: string;
  language: string;
}
